//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeleznicka_stanica.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DodatnaStanica
    {
        public int DodatnaStanicaID { get; set; }
        public int RedVoznjeID { get; set; }
        public System.TimeSpan VremeDolaska { get; set; }
        public System.TimeSpan VremePolaska { get; set; }
        public int StanicaID { get; set; }
    
        public virtual RedVoznje RedVoznje { get; set; }
        public virtual Stanica Stanica { get; set; }
    }
}
