//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeleznicka_stanica.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedVoznje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RedVoznje()
        {
            this.DodatnaStanica = new HashSet<DodatnaStanica>();
        }
    
        public int RedVoznjeID { get; set; }
        public int VozID { get; set; }
        public System.DateTime Datum { get; set; }
        public System.TimeSpan Vreme { get; set; }
        public int Peron { get; set; }
        public bool Kasni { get; set; }
        public Nullable<int> Cena { get; set; }
        public Nullable<bool> Otkazan { get; set; }
        public int PolazakID { get; set; }
        public int OdredisteID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DodatnaStanica> DodatnaStanica { get; set; }
        public virtual Stanica Stanica1 { get; set; }
        public virtual Stanica Stanica11 { get; set; }
        public virtual Voz Voz { get; set; }
    }
}
