//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeleznicka_stanica.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voz()
        {
            this.RedVoznje = new HashSet<RedVoznje>();
        }
    
        public int VozID { get; set; }
        public int BrojMesta { get; set; }
        public int BrojSlobodnihMesta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RedVoznje> RedVoznje { get; set; }
    }
}
